feat: add Publish UI workflow fails prompt.

diff --git a/.github/workflows/publish_ui.yml b/.github/workflows/publish_ui.yml
--- a/.github/workflows/publish_ui.yml
+++ b/.github/workflows/publish_ui.yml
@@ -35,6 +35,14 @@ jobs:
           echo "VERSION_EXISTS=false" >> $GITHUB_ENV
         fi
 
+    - name: Check Core CI status
+      if: >
+        github.event.workflow_run.conclusion == 'failure' ||
+        github.event.workflow_run.conclusion == 'cancelled'
+      run: |
+        echo "The triggering workflow failed or was cancelled. The conclusion is ${{ github.event.workflow_run.conclusion }}."
+        exit 1 # Exit with a failure
+
     - name: Install dependencies
       if: ${{ env.VERSION_EXISTS == 'false' }}    
       run: yarn
