ci: change order

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -45,6 +45,14 @@ jobs:
         with:
           name: dist-artifacts
           path: packages
+      - name: Check Test CI status
+        if: >
+          github.event.workflow_run.conclusion == 'failure' ||
+          github.event.workflow_run.conclusion == 'cancelled'
+        run: |
+          echo "The 'Test CI' workflow is ${{ github.event.workflow_run.conclusion }}."
+          exit 1 # Exit with a failure
+      
       - name: Check version
         id: check
         run: |
@@ -60,20 +68,12 @@ jobs:
             echo "VERSION_EXISTS=false" >> $GITHUB_ENV
           fi
       
-      - name: Check Test CI status
-        if: >
-          github.event.workflow_run.conclusion == 'failure' ||
-          github.event.workflow_run.conclusion == 'cancelled'
-        run: |
-          echo "The 'Test CI' workflow is ${{ github.event.workflow_run.conclusion }}."
-          exit 1 # Exit with a failure
-      
       - name: Publish
         if: ${{ env.VERSION_EXISTS == 'false' }}
         run: |
           yarn config set -H npmScopes.data-story.npmPublishRegistry "https://registry.npmjs.org/"
           yarn config set -H npmScopes.data-story.npmAuthToken "${{ secrets.NPM_DATA_STORY }}"
-          cd packages/ui && yarn npm publish --access public
+          cd packages/core && yarn npm publish --access public
     
   publish_ui:
     needs: publish_core
