ci: delete core_publish build

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -7,7 +7,7 @@ on:
     types: [ completed ]
 
 jobs:
-
+  
   publish_core:
     runs-on: ubuntu-latest
     defaults:
@@ -37,25 +37,28 @@ jobs:
             echo "VERSION_EXISTS=false" >> $GITHUB_ENV
           fi
       
+      - name: Check Test CI status
+        if: >
+          github.event.workflow_run.conclusion == 'failure' ||
+          github.event.workflow_run.conclusion == 'cancelled'
+        run: |
+          echo "The 'Test CI' workflow is ${{ github.event.workflow_run.conclusion }}."
+          exit 1 # Exit with a failure
       - name: Install dependencies
         if: ${{ env.VERSION_EXISTS == 'false' }}
         run: yarn
       
       - name: Build
         if: ${{ env.VERSION_EXISTS == 'false' }}
-        run: yarn tsc
-      
-      - name: Bundle
-        if: ${{ env.VERSION_EXISTS == 'false' }}
-        run: npx webpack
+        run: yarn build
       
       - name: Publish
         if: ${{ env.VERSION_EXISTS == 'false' }}
-        run: npm publish
-        
-        env:
-          NODE_AUTH_TOKEN: ${{ secrets.NPM_DATA_STORY }}
-   
+        run: |
+         yarn config set -H npmScopes.data-story.npmPublishRegistry "https://registry.npmjs.org/"
+         yarn config set -H npmScopes.data-story.npmAuthToken "${{ secrets.NPM_DATA_STORY }}"
+         yarn npm publish --access public
+ 
   
   publish_ui:
     needs: publish_core
@@ -83,12 +86,12 @@ jobs:
             echo "VERSION_EXISTS=false" >> $GITHUB_ENV
           fi
       
-      - name: Check Core CI status
+      - name: Check Core Publish status
         if: >
           github.event.workflow_run.conclusion == 'failure' ||
           github.event.workflow_run.conclusion == 'cancelled'
         run: |
-          echo "The 'Core CI' workflow is ${{ github.event.workflow_run.conclusion }}."
+          echo "The 'Core Publish' workflow is ${{ github.event.workflow_run.conclusion }}."
           exit 1 # Exit with a failure
       
       - name: Install dependencies
